name: Test this action
on:
  push:
    branches-ignore:
    - v1
    tags-ignore:
    - '*'
    paths-ignore:
    - README.md
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04 ]
        # Use various version syntaxes here for testing
        ruby: [ .ruby-version ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ruby --version
    - run: ruby -e "system(RbConfig.ruby, '-e', 'p(:foo)')"
    - run: echo $PATH
    - run: echo $HOME
    - run: ls -la /home
    - run: ls -la $HOME
    - run: ls -la /
    - run: ls -la /opt
    - run: ls -la /opt/hostedtoolcache
    - run: ls -la /opt/hostedtoolcache/Ruby
    - run: ls -la /opt/hostedtoolcache/Ruby/2.5.7
    - run: ls -la /opt/hostedtoolcache/Ruby/2.5.7/x64
    - run: ls -la /opt/hostedtoolcache/Ruby/2.5.7/x64/bin

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn run lint
