name: Test this action
on:
  push:
    branches-ignore:
    - v1
    tags-ignore:
    - '*'
    paths-ignore:
    - README.md
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04 ] #, macos-latest, windows-latest ]
        # Use various version syntaxes here for testing
        ruby: [ .ruby-version, 2.3, 2.7.0, ruby-head ] #, jruby, truffleruby, truffleruby-head, rubinius ]
        exclude:
        - os: windows-latest
          ruby: truffleruby
        - os: windows-latest
          ruby: truffleruby-head
        - os: ubuntu-16.04
          ruby: rubinius
        - os: macos-latest
          ruby: rubinius
        - os: windows-latest
          ruby: rubinius
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        ruby-version: ${{ matrix.ruby }}
        fix-home-permissions: true
    - run: ruby --version
    - run: ruby -e "system(RbConfig.ruby, '-e', 'p(:foo)')"
    - run: echo $PATH
    - run: ls -la /usr/share
    - run: ls -la /usr/share/rust
    - run: ls -la /usr/share/rust/.cargo
    - run: ls -la /usr/share/rust/.cargo/bin

    - run: ridk version
      if: matrix.os == 'windows-latest' && !startsWith(matrix.ruby, '2.3')
    - name: OpenSSL version
      run: ruby -ropenssl -e 'puts OpenSSL::OPENSSL_LIBRARY_VERSION'
    - name: OpenSSL test
      run: ruby -ropen-uri -e 'puts open(%{https://rubygems.org/}) { |f| f.read(1024) }'
    - name: C extension test
      run: gem install json:2.2.0 --no-document
    - run: bundle --version
    - run: bundle install
    - run: bundle exec rake --version

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn run lint
